spring.application.name=BackendService
server.port=8080

spring.mongodb.uri=mongodb+srv://yennampraneeth:Praneeth99@stockmanagement.wcfmpxw.mongodb.net/StockManagement?retryWrites=true&w=majority&authSource=admin

spring.mongodb.database=StockManagement

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true